version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - elasticsearch
    command: gunicorn --worker-class gevent --workers 4 --bind 0.0.0.0:5000 run:app

  redis:
    image: redis:6
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  redis_data:
  es_data: 